name: 'Prepare Credentials'
description: 'Prepare Credentials'
inputs:
  aws_role_arn: 
    required: true
  aws_region: 
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS
      run: |
        export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
        echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
        echo AWS_ROLE_ARN=${{ inputs.aws_role_arn }} >> $GITHUB_ENV
        echo AWS_DEFAULT_REGION=${{ inputs.aws_region }} >> $GITHUB_ENV
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
