on:
  push:
    branches: 
    - develop

name: develop

env:
  AWS_ACCOUNT_ID: 858884198044
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::858884198044:role/github_deployment_develop
  BUILD_ENV: develop
  IMAGE_TAG: develop-${{ github.sha }}
  TASK_DEFINITION_FILE: simple-community-develop/api-main/task-definition.json
  TARGET_RELEASE_ECR_REPOSITORY: simple-community-api-main
  TARGET_RELEASE_CONTAINER_NAME: api
  DEPLOY_REPO_NAME: simple-community-deploy
  DEPLOY_REPO_REF: refs/heads/develop
  GIT_USER_NAME: Deploy
  GIT_USER_EMAIL: yoshinori.satoh.tokyo@gmail.com
  SLACK_WEBHOOK: ${{ secrets.SIMPLE_COMMUNITY_DEV_SLACK_WEBHOOK }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      status: ${{ job.status }}
    strategy:
      matrix:
        include: 
        - target: release
          ecr_repository: simple-community-api-main
    steps:        
    - name: Docker build
      uses: yoshinori-development/simple-community-actions-build@master
      with: 
        aws_role_arn: ${{ env.AWS_ROLE_ARN }}
        aws_region: ${{ env.AWS_REGION }}
        ecr_repository: ${{ matrix.ecr_repository }}
        image_tag: ${{ env.IMAGE_TAG }}
        build_target: ${{ matrix.target }}

  updateTaskDefinitions:
    name: UpdateTaskDefinitions
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      status: ${{ job.status }}
    steps:        
    - name: Configure AWS Credentials
      uses: yoshinori-development/simple-community-actions-aws-creds@v1
      with: 
        aws_role_arn: ${{ inputs.aws_role_arn }}
        aws_region: ${{ inputs.aws_region }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/${{ inputs.deploy_repo_name }}
        ref: ${{ inputs.deploy_repo_ref }}
        token: ${{ inputs.token }}

    - name: update-task-definitions
      id: update-task-definitions
      run: |
        # ビルドターゲットが増えたらここを改修
        image=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.TARGET_RELEASE_ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        cat ${{ env.TASK_DEFINITION_FILE }} \
        | jq --arg image $image 'select(.containerDefinitions[].name == "${{ env.TARGET_RELEASE_CONTAINER_NAME }}").containerDefinitions[].image |= $image' \
        > tmp
        mv tmp ${{ env.TASK_DEFINITION_FILE }}

    - name: git push
      id: git-push
      run: |
        git config --local user.email ${{ inputs.git_user_email }}
        git config --local user.name ${{ inputs.git_user_name }}
        git branch
        git add ${{ inputs.task_definition_file }}
        git commit -m "[UpdateImageTag] ${{ github.event.repositories.name }} $GITHUB_SHA"
        git push

  slackNotification:
    if: always()
    needs: [updateTaskDefinitions]
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ env.SLACK_WEBHOOK }}
